### ISSUE TITLE
missing code in code-log pair

### ISSUE THREAD

**Issue by coder-chenzhi** [logpai/LoggingDescriptions#2]
I found some missing code of code-log pair in the dataset. They are listed below, please check them.
- Line 10950-10956 in ambari_code_log_pairs.txt
- Line 8961 in brooklyn_code_log_pairs.txt

**Comment by PinjiaHe** [comment]
Thanks for your comment! The code for these pairs seems indeed missing, we will check shortly.

**Comment by zbchern** [comment]
Thanks a lot for your comment!

The issue happens because the arguments of some functions contain special symbols like @, which makes us fail to recognize the complete body of these functions. This is indeed a corner case and we have fixed the problem for all projects (if any).
